### ISSUE TITLE
How to install mathlib?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#10]
Mathlib for lean is here
https://github.com/leanprover/mathlib
It contains some basic math definitions and theorems, and is used in Theorem Proving in Lean, chapter 5.

I have downloaded mathlib but don't know how to make VSCode understand where it is. A temporary and hacky solution is to copy paste the files to the 
`/lean-3.3.0-darwin/lib/lean/library`
folder, but that's hacky.

**Comment by semorrison** [comment]
The best way to use `mathlib` is to learn to use `leanpkg`. If you've got `lean` working on the command line, you should also be able to run `leanpkg`.

There is some documentation at <https://github.com/leanprover/lean/tree/master/leanpkg>.

I'm actually right now trying to create a package that spans the whole shared Dropbox folder, but running into some troubles!

**Comment by semorrison** [comment]
There's a momentary incompatibility between the master version of Lean and the master version of mathlib. (cf https://gitter.im/leanprover_public/Lobby?at=5a17f49c8b3a9e2c0c11647f). Once this is fixed I'll show everyone how to install mathlib.

**Comment by semorrison** [comment]
I've added mathlib to our repository. If in the main directory of the repository you run `leanpkg build` it should successfully compile a whole lot of stuff.

After that, if you open, for example `Scott/20171124-decimals.lean`, you should be able to successfully run imports like `import data.rat` or `import analysis.real` to get access to the rational numbers or the real numbers.

(Notice there's an error message when I run `#eval` with real numbers, because the current construction is non-constructive!)

**Comment by yuxiliu-anu** [comment]
just a note: to make "leanpkg" into a command in terminal, use a soft link like
`sudo ln -s <pathname>/lean/bin/leanpkg /usr/sbin`

**Comment by yuxiliu-anu** [comment]
I have compiled the latest version of lean, and run leanpkg in the main folder. It seemed to have encountered errors, and 
`external command exited with status 256`
And `import data.rat` or `import analysis.real` does not work.

**Comment by semorrison** [comment]
Usually exit code 256 means that it can't find a binary. What happens if
you use the absolute path for leanpkg? What about if instead of
soft-linking leanpkg and lean in /usr/sbin, you just add the lean/bin
directory to your PATH?

**Comment by yuxiliu-anu** [comment]
There was no difference.
It seems the compilation was successful the first time I ran leanpkg in the main folder, then it would not need to compile them again. 

Now when I run it, it started by
```
configuring 2017-summer-students 0.1
mathlib: trying to update _target/deps/mathlib to revision 2c84af163dbc83c6eb6a94a03d5c25f25b6b8623
> git checkout --detach 2c84af163dbc83c6eb6a94a03d5c25f25b6b8623    # in directory _target/deps/mathlib
HEAD is now at 2c84af1... feat(data/set/finite): unify fintype and finite developments
```
then it started trying to compile our lean files and giving errors like
```
> lean --make .
.../2017-summer-students/Scott/20171124-colons.lean:4:16: error: invalid definition, '|' or ':=' expected
```
etc, finding lots of errors in our lean files. The ending is
```
.../2017-summer-students/Louis Carlin/tests.lean:74:0: warning: result type does not have an instance of type class 'has_repr', dumping internal representation
(#1 (#1 #0))
external command exited with status 256
```

**Comment by semorrison** [comment]
Oh --- that sounds like it is working! For example the error in
20171124-colons.lean,
is expected -- it's just a copy of your issue #3.

You can tell if mathlib is working if you can open
Scott/20171124-decimals.lean and _not_ see an error on the first two lines,
where we import things from mathlib.

**Comment by semorrison** [comment]
Ah, my mistake! To get VS Code to use mathlib, you can't just open the individual Lean file, it seems.  You should open the entire folder `2017-summer-students` in VS Code, and then use VS Code's navigator to open the individual files. Otherwise it doesn't seem to find the dependencies correctly.

**Comment by semorrison** [comment]
(Also, I'm also currently seeing the `external command exited with status 256` message, with no apparent ill effects.)

**Comment by yuxiliu-anu** [comment]
I think it is working for me now.
