### ISSUE TITLE
Meeting time.

### ISSUE THREAD

**Issue by louisanu** [semorrison/2017-summer-students#12]
I think Scott's suggestion of meeting up is a good idea.

I'm probably going to be away this monday to thursday (depends if I can get time off work), so either Saturday or Sunday is best for me.
Saturday I can do anytime past 2:30.
Sunday I am free from 2:30 to 5:30.

 If neither day works for you guys then feel free to get started while I'm away.

**Comment by MitchRowett** [comment]
I can do Saturday or any time next week.

**Comment by yuxiliu-anu** [comment]
I can do everyday past 12:30 up to December 8, then I'll be away from Canberra until January 22.

**Comment by yuxiliu-anu** [comment]
Let's meet today at 2:30 in the common room of John Dedman. I'll be there and I'll bring vegetarian cookies.


> John Dedman is open during the day, and you can use the common room, or perhaps better the meeting room next to it. (The door code is CY1973. If you like you can tell me a time and I'll book it for you so you have priority.)

**Comment by semorrison** [comment]
I booked the meeting room, JD 1177, for you guys all afternoon.

**Comment by louisanu** [comment]
2:30 sounds good, see you then.

**Comment by MitchRowett** [comment]
See you then.

**Comment by louisanu** [comment]
We're not sure how to get into John Dedman. Both of the doors at the back don't open.

**Comment by semorrison** [comment]
Ah, sorry about that. It didn't occur to me none of you would have swipe
card access. Hopefully you've worked something out.

**Comment by yuxiliu-anu** [comment]
I suggest that for backup meeting location, Chiefley Library Level 3. It's open 24/7
http://anulib.anu.edu.au/news-events/news/chifley-level-3-now-open-247
