### ISSUE TITLE
Please upgrade to the latest version of Lean

### ISSUE THREAD

**Issue by semorrison** [semorrison/2017-summer-students#13]
Unfortunately there was a temporary incompatibility between the main repository and mathlib. As I'd like to be able to show everyone how to use mathlib, I think the best solution is to have everyone upgrade their copy of Lean to the latest version (commit 18cf63e or later).

Please comment here when you've done that, and I'll explain how to use mathlib.

**Comment by MitchRowett** [comment]
My copy is updated (commit 18cf63e).

**Comment by semorrison** [comment]
Reopening this, so I can keep track of who has managed to upgrade. Hopefully this isn't too annoying, but I want to try to keep up with you guys! Generally, if there is an issue "assigned" to multiple people, please just remove yourself once you've done your part, but leave it open if others still need to do it too.

**Comment by felicitylu** [comment]
I have done the upgrading with help from Mitchell and Louis yesterday. But we had the same problem as Yuxi while adding the leanpkg (exit code 256)?

**Comment by louisanu** [comment]
My ancient laptop shuts itself down when I try to compile the new version (I think it's running out of power even though it's plugged in).

I don't anticipate any issues when it comes to my desktop but I don't have access to that for a few days, so I'll be stuck with an older build for the time being.

**Comment by semorrison** [comment]
Okay -- as I said on the other thread, the exit code 256 error seems to be harmless.
