### ISSUE TITLE
Why does the following tactic not work?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#17]
```
inductive xnat 
| zero : xnat
| succ : xnat → xnat

namespace xnat
def one := succ zero
definition two := succ one

def add : xnat → xnat → xnat
| x zero := x
| x (succ y) := succ (add x y)
notation a + b := add a b

meta def trivial_induction : xnat → tactic unit := λ n,
`[ induction n with t Ht, refl, unfold add, rw Ht ]

theorem zero_add (n : xnat) : zero + n = n :=
by (trivial_induction n)
```
The error message is saying
```
_interaction._lambda_3: trying to evaluate sorry

unknown identifier 'n'
```

**Comment by semorrison** [comment]
I've just committed a solution. There are a few things to learn here (which I just learnt!).

1) Tactics that you want to use from inside tactic mode (i.e. in a `begin ... end` block) need to be in the `namespace tactic.interactive`. (Is there a way around this? I don't know.)

2) You can't actually pass an `xnat` to this tactic --- you need to pass an `expression` referring to an `xnat`. This is the meaning of the argument `(p : parse texpr)` to `trivial_induction`. (And also the reason why we have to open a few more namespaces, to get access to `parse` and `texpr`.)

3) Inside the "quotation" ``[ induction %%p with t Ht, refl, unfold add, rw Ht ]`, we need to use the "antiquotation" `%%p`.
