### ISSUE TITLE
Prove a < b ↔ ∃ t : xnat, b = a + succ t

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#19]
Follow https://xenaproject.wordpress.com/2017/10/31/building-the-non-negative-integers-from-scratch/
for question 10, I want to prove 
`a < b ↔ ∃ t : xnat, b = a + succ t`

I tried proving a lemma
`lemma a_less_b_succ (a b : xnat) :  (succ a < b → a < b) ∧ (a < b → a < succ b)`
by induction, but could not make it work.

I did prove 
`lemma total_order_lemma (a b : xnat) : 
  (∃ (t : xnat), a = b + succ t) ∨ a = b ∨ (∃ (t : xnat), b = a + succ t)`

**Comment by semorrison** [comment]
Hi Yuxi,

could you post some self contained code that we can try out? If you make a commit in git and include the issue number (e.g. #19 for this one), it will make a link right here on the issue page.

Then it's easier for others to try filling in a proof!

**Comment by yuxiliu-anu** [comment]
My current feeling is that the core of the problem is proving that < is asymmetric. That seems to require a serious double recursion which I can't make it do.

**Comment by yuxiliu-anu** [comment]
I had an epiphany about this just as I was waking up. The problem was that, in showing the proposition
`∀ m n, P(m, n)`
It's usually better to assume m, then induct on m, then assume n, then induct on n.
Not assume m, then assume n, then induct on m, then induct on n.
So in Lean code, it's like

```
intro m, 
  induction m with m Hm,
    -- Prove ∀n, P(0, n)
    intro n,
    induction n with n Hn,
      -- Prove P(0, 0)
      -- Prove P(0, n + 1), given P(0, n)
  -- Prove ∀n, P(m + 1, n), given ∀n, P(m, n)
  intro n,
  induction n with n Hn,
    -- Prove P(m + 1, 0), given ∀n, P(m, n)
  -- Prove P(m + 1, n + 1), given P(m + 1, n), and ∀n, P(m, n)
```

**Comment by semorrison** [comment]
Looks good! :-)
