### ISSUE TITLE
Are the projects only for learning or actually going to be published?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#21]
#16 and #14 seem to be done already, so they are probably only for learning. Is #15 going to be for learning or for publishing?

And in general what projects would be for learning and what would be for publishing?

**Comment by semorrison** [comment]
Hi Yuxi,

nothing at the level of the projects #14, #15, #16 is "publishable", in the sense of turning it into an article for a peer-reviewed journal.

On the other hand, clean code in those directions could certainly be incorporated into mathlib for Lean, or standalone Lean packages that we can publish on github for others to use.

best,
Scott

**Comment by yuxiliu-anu** [comment]
That's nice to hear.

Such helpful comments should be kept in some wiki page for later reading, before closing the issue, but what should the page title be?
