### ISSUE TITLE
What does Type "universe" do?

### ISSUE THREAD

**Issue by felicitylu** [semorrison/2017-summer-students#22]
**A file for this: [Here](https://github.com/semorrison/2017-summer-students/blob/master/Fei/type.lean)**

It was just mentioned briefly in the tutorial (End of 2.2) but I got a bit confused. I got the part when we use the default Types and `[Lean] prod : Type u_1 → Type u_2 → Type (max u_1 u_2)`:
`constant α : Type`
`#check prod α α`
where `prod α α` is a Type.

But if I do
`universe u`
`constant α : Type u`
`#check α`
`#check prod α α`
The latter one shows`Type max(u_1 u_2)`. Is `α` just `Type u_1`? Where does the `Type u_2` coming from?

**Comment by semorrison** [comment]
Someone on gitter just pointed out that if you explain `constant` in your code with `variable`, then it behaves as expected. I don't really know what to make of that.

**Comment by felicitylu** [comment]
All good then! I guess it is just some hidden properties of `constant` and `variable`... 

The tutorial says
> The `variable` and `variables` commands look like the `constant` and `constants` commands we have used above, but there is an important difference. Rather than creating permanent entities, the former commands simply instruct Lean to insert the declared variables as bound variables in definitions that refer to them.

which was not very clear either. I hope there would be more explanation in Chpt.3.

Thank you very much!

**Comment by felicitylu** [comment]
Ah, I see comments from [Rob](https://gitter.im/leanprover_public/Lobby?source=all-rooms-list). It really helped. I was wondering what "polymorphic" means at first and it is all clear now. 

So `variable` should be defined uniquely in the whole file and `constant` is polymorphic among different type universes. Is it right?

**Comment by semorrison** [comment]
There are then some further helpful comments from Mario on gitter: https://gitter.im/leanprover_public/Lobby?at=5a1cfd42232e79134dde9867
