### ISSUE TITLE
Difference between #reduce ff && b and  #reduce b && ff

### ISSUE THREAD

**Issue by felicitylu** [semorrison/2017-summer-students#23]
`#reduce ff && b ` gives `ff` (as we might expect), while `#reduce b && ff`gives `bool.rec ff ff b`. What exactly does that mean?

I found an existing post on this problem: [capturing output of #print computation / manual / real numbers](https://groups.google.com/forum/#!topic/lean-user/y6fRK4dpayU). It did not help much though... When I try
`#print bool.rec`
it gives 
`Lean] protected eliminator bool.rec : Π {C : bool → Sort l}, C ff → C tt → Π (n : bool), C n`
in which I do not see `band`, `band._main` and `bool.cases`mentioned in this post. Have I missed anything here?

**Comment by semorrison** [comment]
Here's some code:

````
variable b: bool

#reduce b && ff
#print bool.rec

set_option pp.all true

#reduce b && ff
#print bool.rec
````

(By the way, I strongly recommend committing a file and linking to it for most questions -- it makes it easier for everyone else to reproduce what you're doing. Even just copying and pasting your entire code into the question, or to gist.github.com is helpful.)

As you said in your post, the type of `bool.rec` is `Π {C : bool → Sort l}, C ff → C tt → Π (n : bool), C n`. How do we read this? It says: "if you give me a family of types, `C`, indexed by booleans, and a term of type `C ff`, and a term of type `C tt`, then I'll give you a term of type `C n` for every boolean `n`.

That's just a fancy way of saying: to do something with a boolean, it's enough to know what to do with the values `tt` and `ff`.

Now, the output of `#reduce b && f` is still not super helpful: `bool.rec ff ff b`. If we turn on the most verbose options for the pretty printer (using `set_option pp.all true`, as above), we get to see the implicit arguments. (Notice the `{ ... }` in the type of `bool.rec`: that says the the argument `C` is implicit and needn't be displayed in most cases.) Now `#reduce b && f` says

`@bool.rec.{1} (λ (a : bool), bool) bool.ff bool.ff b`

What does that mean? First the `@` at the beginning just indicates that implicit arguments are being shown. The `.{1}` is something about universes, don't worry for now! Next, we get the see the implicit argument which was hidden, namely `C`. This just says: whatever boolean `a` you give me, the type `C a` is just `bool`. Finally, the remaining arguments are `bool.ff`, `bool.ff`, and `b`. We can see this means: "If `b` is false, return the value `bool.ff`. On the other hand, if `b` is true, return the value `bool.ff`."

Why Lean doesn't reduce this all the way down to `bool.ff` for us, I don't really know. :-)
