### ISSUE TITLE
Move Projects to "Projects"?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#24]
There's actually a project tab in github. I wonder if that's a better place for the projects? 
It seems to be for collaborative projects, and for now we are just doing our own versions of the small projects, but if we eventually want to write a project together that might be useful?

**Comment by semorrison** [comment]
@yuxiliu-anu, feel free to try it out for one; if it seems useful we can migrate the other issues tagged "project", too.
