### ISSUE TITLE
Glitches of Tutorial Section 2.9

### ISSUE THREAD

**Issue by felicitylu** [semorrison/2017-summer-students#26]
I do not know if I need to raise this up... It is just a small issue.

It seems a bad idea to name our re-defined concepts with the same name as the existing ones. And naming a namespace the same as a definition is confusing as well...

So here is the thing. `variables l1 l2 : list α` in the original codes (and some other block of codes, same thing)
```
namespace list
  constant cons   : Π {α : Type u}, α → list α → list α
  constant nil    : Π {α : Type u}, list α
  constant append : Π {α : Type u}, list α → list α → list α
end list

open hide.list

variable  α : Type
variable  a : α
variables l1 l2 : list α

#check cons a nil
#check append (cons a nil) l1
#check append (append (cons a nil) l1) l2
```
does not work. We shall either change it to [hide.list α](https://github.com/semorrison/2017-summer-students/blob/master/Fei/namespace1.lean), or work in [namespace hide](https://github.com/semorrison/2017-summer-students/blob/master/Fei/namespace2.lean) for the entire time.

Another question, does `open` do a permanent opening of the namespace? (There is no `close` available)

**Comment by semorrison** [comment]
I'd suggest if you're creating toy versions of basic things like `list` or `nat` you name them as `xlist` or `xnat`, etc.

You can't undo `open`ing a namespace, except by closing a section that you're working in.
