### ISSUE TITLE
How to uncurry functions?

### ISSUE THREAD

**Issue by felicitylu** [semorrison/2017-summer-students#27]
I tried to work on exercises but had some problems getting `uncurry` done. And I do not know how to write the `curry` process without `λ` (defining types within the definition). 

I do not get how `(x,y)` is recognised in some cases and not working in some others. `prod x y` is not very reliable either...

Here are the [codes](https://github.com/semorrison/2017-summer-students/blob/master/Fei/curry.lean).

**Comment by semorrison** [comment]
For sections U and V, I think you just want:

````
section U
variables α β γ : Type
def uncurry : (α → β → γ) → α × β → γ := λ f p, f p.1 p.2
#print uncurry
end U
-- Why is uncurry not working?

section V
def vuncurry (α β γ : Type) (f : α → β → γ): α × β → γ := λ p, f p.1 p.2
#print bcurry
end V
````

**Comment by semorrison** [comment]
I don't really understand what you're looking for in B. Won't

````
section B
def bcurry (α β γ : Type) (f : α × β → γ) : α → β → γ := λ x y, f(x,y)
#print bcurry
end B
````
do? Perhaps you should tell me which exercises you're looking at.

**Comment by semorrison** [comment]
I can't tell in section C what you're trying to do.

**Comment by felicitylu** [comment]
Section C was nonsense. I was just trying to match up the types required for input and output...

Section B was the way defining things without `λ`, like
`def compose (α β γ : Type) (g : β → γ) (f : α → β) (x : α) : γ := g (f x)`. 

But I think you are right... The question was just to replace the `sorry` here:
`def curry (α β γ : Type) (f : α × β → γ) : α → β → γ := sorry`

So it would work!

**Comment by felicitylu** [comment]
I get the part for `uncurry`. Simple as that! But why could not we use `f (x,y)` this time?

**Comment by semorrison** [comment]
For uncurry, we have `f : α → β → γ`. That is, it is a function which takes an `α`, and produces a function `β → γ`. You can't apply such a function to a pair `(x, y) : α × β`. That's the point of currying and uncurrying!

**Comment by semorrison** [comment]
If you want to write `uncurry` without using the symbol `λ`, you could for example write

`def uncurry ( f: α → β → γ ) ( p : α × β ) := f p.1 p.2`

then `uncurry f` has type `α × β → γ` as desired.
