### ISSUE TITLE
Meeting on Friday

### ISSUE THREAD

**Issue by MitchRowett** [semorrison/2017-summer-students#28]
Would anyone be interested in meeting again this Friday? Perhaps at 11 (a completely arbitrary time, so if anyone has any reason to prefer a different time I'm happy to change).

Scott, has there been any update on getting card access to JD?

**Comment by semorrison** [comment]
Kelly said that it was too difficult to get you all after hours access to JD. The building itself is unlocked 8am-6pm Monday to Friday.

**Comment by yuxiliu-anu** [comment]
What would you like to discuss?
I don't think we have much to discuss yet. I don't want a meeting, unless the professor would come too.

**Comment by semorrison** [comment]
I won't be available this Friday, but can meet with everyone next week sometime Wed-Fri.

I'd encourage those of you who do want to meet, to do so, but it's certainly not essential.

**Comment by felicitylu** [comment]
Scott, could I book a meeting with you sometime next week? 

Friday 11am at JD is good for me. I would come if my knee does not hurt too bad tomorrow... tripped over on road this morning :(
