### ISSUE TITLE
Strange behavior of keyword "example" followed by colons

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#3]
variables p q : Prop

example : (p → q) → p → p := λ _ (hp : p), hp -- fine
example (p → q) → p → p := λ _ (hp : p), hp -- not fine

example : p → q → p → p := λ _ _ (hp : p), hp -- fine
example p → q → p → p := λ _ _ (hp : p), hp -- not fine
example p → q → p → p := λ (_ : p) (_ : q) (hp : p), hp -- fine

example p → q → (p → p) := λ (_ : p) (_ : q) (hp : p), hp -- fine
example (p → q) → p → p := λ (_ : p → q) (hp : p), hp -- not fine
example : (p → q) → p → p := λ (_ : p → q) (hp : p), hp -- fine

Why?

**Comment by louisanu** [comment]
None of the ones without a colon work for me.

I get `[Lean] invalid binder declaration, delimiter/bracket expected (i.e., '(', '{', '[', '{{')` for both.

What are you intending to do by excluding the colon?

**Comment by semorrison** [comment]
Me too --- the colons seem necessary. (If you're not seeing this, reopen and we can diagnose.)
