### ISSUE TITLE
refl curiosity

### ISSUE THREAD

**Issue by louisanu** [semorrison/2017-summer-students#30]
I noticed that the `refl` tactic can replace a line of code in one situation but can't replace the exact same code in another. I was wondering if anyone had an explanation.

```
theorem right_distrib (a b c : xnat) : a * (b + c) = a*b +a*c :=
begin
induction b with k hk,
    induction c with l hl,
        rw [zero_add, mul_zero, zero_add], -- refl can be used to replace this
        rw [zero_add, mul_zero, zero_add], -- refl does not work here (invalid apply tactic, failed to unify)
        rw <- add_succ,
        unfold mul,
        rw hk,
        exact eq.symm (add_assoc a (a*k) (a*c))
end
```

The definitions this relies on are in my xnat.lean file.

**Comment by yuxiliu-anu** [comment]
Try these two lines instead
```
        rw [add_zero, mul_zero, add_zero],
        rw [zero_add, mul_zero, zero_add],
```
Notice that the first line uses add_zero and mul_zero, both of which are proved by unfolding the definition. refl is clever enough to unfold definitions. 
The second line uses zero_add, which must be proved by induction, not by unfolding the definition. refl is too dumb to do that.
