### ISSUE TITLE
Questions about Exercises of Chpt.3

### ISSUE THREAD

**Issue by felicitylu** [semorrison/2017-summer-students#32]
I have got some troubles completing the exercises of Chapter 3. Could someone give me a hint?
[All Codes Are Here](https://github.com/semorrison/2017-summer-students/blob/master/Fei/chpt3.lean)

The first one is with 
```
-- (11) B
example : ¬(p ↔ ¬p) := 
  assume h : p ↔ ¬p,
  have hpnp : p → ¬p, from h.mp,
  have hnpp : ¬p → p, from h.mpr,  
  show false, from sorry
```
I have written a proof using `by_cases`, but it seems to be using the excluded middle rule. How to prove it without classical logic?

And other problems are similar. When using the classical logic, how to prove a case that does not cooperate with our original assumption? like
```
-- (3)
example : ¬(p → q) → p ∧ ¬q := 
assume h : ¬(p → q), 
  by_cases
  (assume hp : p,
    by_cases 
    (assume hq : q, 
      have hpq : p → q, from (assume hp, hq),
      show p ∧ ¬q, from false.elim (h hpq))
    (assume hnq : ¬q, show p ∧ ¬q, from ⟨hp, hnq⟩)
  )
  (assume hnp : ¬p, 
    show p ∧ ¬q, from sorry
  )
```
I was trying to prove it by the idea of`absurd p ¬p`, but it does not work sometimes.

Thank you!

**Comment by yuxiliu-anu** [comment]
try 
`absurd ¬p ¬¬p`

**Comment by felicitylu** [comment]
Thank you!

**Comment by felicitylu** [comment]
Sorry, I am afraid I am still not getting it right... 

For (Q1), do I need to have `assume hp : p` somewhere? If so, how do I move it out of the system (not making the whole structure like `p ↔ ¬p → p → false` for instance?

For (Q2), how could I get `(p → q)` with `assume hnp : ¬p`?

**Comment by yuxiliu-anu** [comment]
Q1
```
example : ¬(p ↔ ¬p) :=
    have h1 : (p → ¬p) → ¬p, from 
        assume h11 : p → ¬p, assume h12 : p,
        h11 h12 h12,
    have h2 : (¬p → p) → ¬¬p, from 
        assume h21 : ¬p → p, assume h22 : ¬p,
        h22 (h21 h22),
    assume h : p ↔ ¬p, absurd (h1 h.elim_left) (h2 h.elim_right)
```

Q2
`assume hnp : ¬p, 
have hpq : (p → q), from
  assume hp : p, 
  absurd hp hnp`
