### ISSUE TITLE
Lean issues

### ISSUE THREAD

**Issue by louisanu** [semorrison/2017-summer-students#34]
I updated to the latest lean version and it doesn't run very well.
At first it was taking ages to display tactics goals and I'm now get the error `[Lean] excessive memory consumption detected at 'expression equality test' (potential solution: increase memory consumption threshold)` for all of the theorems in my xnat.lean file.
Scott seemed to have a similar issue but I wasn't quite sure how he solved it.
When I ran `leanpkg build` to install mathlib (I don't know if I need to do this every time I update?) it froze parsing line 12 of 20171124-decimals.lean (and eventually froze my computer).

Edit: Restarting seems to fix the memory issue. I wonder if there is some kind of memory leak.

**Comment by semorrison** [comment]
I've rearranged how `leanpkg` works here, so by default `leanpkg build` will only compile stuff in the `src` directory (not in our named directories). You can still import things from `mathlib` from any subfolder, and if you run `leanpkg build` first, a little stub I put in the `src` directory will make sure that all the basic stuff in `mathlib` gets compiled.
