### ISSUE TITLE
Equivalence Relation to get a Quotient Group

### ISSUE THREAD

**Issue by MitchRowett** [semorrison/2017-summer-students#38]
The construction of a quotient group G/N that I'm using requires the definition of an equivalence relation on elements of G. Currently, the equivalence relation that I'm using is `x * y⁻¹ ∈ N`.

However, I think it's a much more natural construction to make the equivalence relation `xN = yN`. Doing this requires me to restructure my current definition of cosets, but I think will be far more versatile in the long run.

What do you think? I should be able to commit the revised version later this afternoon.

**Comment by semorrison** [comment]
I guess I'm not sure what difference you think it will make?

**Comment by MitchRowett** [comment]
I had initially thought that there was a cleaner way of constructing the quotient groups using that definition, but I've now realised that the cleaner construction is actually possible with either equivalence relation. Do you think there's any benefit of one over the other?

Also, is it possible to meet on some time on Monday to discuss how I should structure the report?
