### ISSUE TITLE
Rewriting only once

### ISSUE THREAD

**Issue by MitchRowett** [semorrison/2017-summer-students#39]
Is there a way to make the rewrite tactic apply at one place in a goal, and not somewhere else?

For example, at line 114 of coset.lean (in the proof of mem_own_coset) the goal is `a ∈ a * S`. Applying `rw [←mul_one a]` causes the goal to become `a * 1 ∈ a * 1 * S`, when really I wanted it to become `a * 1 ∈ a * S`.

**Comment by semorrison** [comment]
Have a look at `conv`. There are some examples in Lean's changes.md, and
perhaps a closed issue here, but not much documentation otherwise.
