### ISSUE TITLE
"Infer type failed" error

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#5]
```
variables (α : Type) (a b : α)
example : ∀ (p : α → Prop), a = b → p a → p b :=
  assume h1 : a = b,
  assume h2 : p a, 
  h1 ▸ h2
```

why is this giving error 
```
infer type failed, function expected at
  h1 a
term
  h1
has type
  a = b
``` 
Yet the next one works?

```
variables (α : Type) (a b : α)
example (p : α → Prop) : a = b → p a → p b :=
  assume h1 : a = b,
  assume h2 : p a, 
  h1 ▸ h2
```

**Comment by semorrison** [comment]
The analogue of `assume` in tactic mode is `intros`. Compare the two alternatives in the attached file. Notice that `intros` needs to introduce 3 new hypotheses in the first example, but only 2 in second example. In your example above, you can't use `assume` yet as you haven't yet introduced `p`.
