### ISSUE TITLE
Default naming of constructors in inductive types?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#8]
In the following code the output is info: `(#1 (#1 0))`. It seems that the interpreter named `my_nat.succ` as `#1`, and `nat.zero` as `0`. Why?

```
inductive my_nat : Type
| zero : my_nat
| succ : my_nat -> my_nat

def one : my_nat := my_nat.succ my_nat.zero

def add : my_nat -> my_nat -> my_nat
| m my_nat.zero := m
| m (my_nat.succ n) := my_nat.succ (add m n)

#eval add one one
```

**Comment by semorrison** [comment]
This I have no idea about. You could ask on the gitter channel `lean/Lobby`. (Just as a word of warning, I've got in trouble for spamming the gitter channel with too many questions in the past, so I'll ask you all to post questions here first, and only once we're stuck suggest asking there.)

**Comment by semorrison** [comment]
I'm just going to close this as one of life's little mysteries. I don't think it's too important.
