### ISSUE TITLE
Adding a variable makes a theorem fail

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#9]
Somehow, this theorem fails unless variable h4 : e = 1 + d is not included.

```
variables (d e : ℕ)
variable h4 : e = 1 + d
include h4 --comment this out
theorem T5 (a b c d : ℕ)
  (h1 : a = b) (h2 : b ≤ c) (h3 : c + 1 < d) : a < d :=
calc
  a     = b     : h1
    ... < b + 1 : nat.lt_succ_self b
    ... ≤ c + 1 : nat.succ_le_succ h2
    ... < d     : h3
```

**Comment by semorrison** [comment]
This one looks like a problem in Lean. Well done! :-)

I would suggest we ask on the gitter channel first, to see if anyone there knows what's happening, and if they agree it looks suspicious we can _then_ post an issue on the main Lean site. Yuxi, do you want to write a draft of what you might say to describe this issue (e.g. include the relevant part of the error message), and if that looks good you can ask? (If you prefer I can ask, too.)

**Comment by yuxiliu-anu** [comment]
# Draft:

Somehow, this theorem fails unless variable h4 : e = 1 + d is not included.

```
variables (d e : ℕ)
variable h4 : e = 1 + d
include h4 --comment this out
theorem T5 (a b c d : ℕ)
  (h1 : a = b) (h2 : b ≤ c) (h3 : c + 1 < d) : a < d :=
calc
  a     = b     : h1
    ... < b + 1 : nat.lt_succ_self b
    ... ≤ c + 1 : nat.succ_le_succ h2
    ... < d     : h3
```
the error message is 
```
kernel failed to type check declaration 'T5' this is usually due to a buggy tactic or a bug in the builtin elaborator
elaborated type:
  ∀ (e : ℕ), e = 1 + d → ℕ → ∀ (a b c d : ℕ), a = b → b ≤ c → c + 1 < d → a < d
elaborated value:
  λ (e : ℕ) (h4 : e = 1 + d) (d a b c d : ℕ) (h1 : a = b) (h2 : b ≤ c) (h3 : c + 1 < d),
    lt_trans (lt_of_lt_of_le (trans_rel_right has_lt.lt h1 (nat.lt_succ_self b)) (nat.succ_le_succ h2)) h3
nested exception message:
failed to add declaration to environment, it contains local constants
```
I am running Lean 3.3.0 downloaded on 2017-11-19, with no added libraries, running on Visual Studio Code with lean extension, on OS X Yosemite.

**Comment by semorrison** [comment]
Looks great! Let's start by posting on the gitter channel, and see if anyone knows what's happening.

**Comment by yuxiliu-anu** [comment]
OK. Can you post it and link to me?

**Comment by semorrison** [comment]
Would you prefer to post it yourself? I don't mind either way.

**Comment by yuxiliu-anu** [comment]
I'm anxious talking to strangers.

**Comment by semorrison** [comment]
No worries. I've posted it at <https://gitter.im/leanprover_public/Lobby?at=5a18a4d58b3a9e2c0c14ed60>.

**Comment by MitchRowett** [comment]
For prosperity, I'll copy the answer over here. Sadly, the issue was not nearly as exciting as we originally thought.

> The elaborated value has two ds
> You are forcing one in with the include and then adding another one 

```
variable (d : ℕ)
variable h4 : d = d
include h4 --comment this out to make things work
theorem T5 (d : ℕ) : d = d := rfl
```
